# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabriel Pascua
description: > # this means to ignore newlines until "baseurl:"
  Personal Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gabrielpascua.com" # the base hostname & protocol for your site
github_username:  gabrielpascua

# Build settings
markdown: kramdown

# Github Injected Configuration
# https://help.github.com/articles/configuring-jekyll/
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

kramdown:
   input: GFM
   hard_wrap: false
   math_engine: mathjax
gems:
   - jekyll-paginate

paginate: 11
paginate_path: "/notes/page/:num/"